import fs from "node:fs/promises";
import path from "node:path";
import type { AstroIntegration, AstroIntegrationLogger } from "astro";
import { tryParse } from "./parser";

type InlineOptions = {
    mode: "inline";
    /** Directory scanned for .source.fsx files and where .mdx files are written. Defaults to "src/content/docs". */
    base?: string;
};

type MirrorOptions = {
    mode: "mirror";
    /** Directory scanned for .source.fsx files. Defaults to "src/content/fsharp-literate". */
    sourceDir?: string;
    /** Directory where generated .mdx files are written, mirroring the sourceDir structure. Defaults to "src/content/docs". */
    outputDir?: string;
    /** Extensions for source files. Defaults to [".fsx", ".fs"]. */
    sourceExtensions?: string[];
    /** Force output file name to lowercase */
    forceLowerCaseOutputFileName?: boolean;
};

export type Options = InlineOptions | MirrorOptions;

interface ResolvedConfig {
    mode: "inline" | "mirror";
    sourceDir: string;
    outputDir: string;
    sourceExtensions: string[];
    forceLowerCaseOutputFileName: boolean;
}

/** Normalises user-facing options into a consistent internal shape used throughout the plugin. */
function resolveConfig(options?: Options): ResolvedConfig {
    if (options?.mode === "mirror") {
        return {
            mode: "mirror",
            sourceDir: path.resolve(options.sourceDir ?? "src/content/fsharp-literate"),
            outputDir: path.resolve(options.outputDir ?? "src/content/docs"),
            sourceExtensions: options.sourceExtensions ?? [".fsx", ".fs"],
            forceLowerCaseOutputFileName: options.forceLowerCaseOutputFileName ?? false
        };
    }

    const base = path.resolve(options?.base ?? "src/content/docs");
    return {
        mode: "inline",
        sourceDir: base,
        outputDir: base,
        sourceExtensions: [".source.fsx", ".source.fs"],
        forceLowerCaseOutputFileName: false,
    };
}

/**
 * Recursively collects all source files matching any of `sourceExtensions` under `dir`.
 * @param dir Directory to scan.
 * @param sourceExtensions File extensions to match (e.g. `[".source.fsx", ".source.fs"]`).
 * @returns An array of absolute file paths.
 */
async function collect(dir: string, sourceExtensions: string[]): Promise<string[]> {
    const entries = await fs.readdir(dir, { withFileTypes: true, recursive: true });
    return entries
        .filter(entry => entry.isFile() && sourceExtensions.some(ext => entry.name.endsWith(ext)))
        .map(entry => path.join(entry.parentPath, entry.name));
}

/**
 * Returns the output `.mdx` path for a given source file.
 *
 * In inline mode the output sits next to the source; in mirror mode it is
 * replanted under `outputDir`, preserving the relative directory structure.
 *
 * @param sourcePath Absolute path of the source file.
 * @param config Resolved plugin configuration.
 * @returns Absolute path of the output `.mdx` file.
 */
function mdxPath(sourcePath: string, config: ResolvedConfig): string {
    const ext = config.sourceExtensions.find(e => sourcePath.endsWith(e))!;
    if (config.mode === "inline") {
        return sourcePath.slice(0, -ext.length) + ".mdx";
    }
    const rel = path.relative(config.sourceDir, sourcePath);
    return path.join(config.outputDir, rel.slice(0, -ext.length) + ".mdx");
}

/**
 * Parses a `.source.fsx` file and writes the corresponding `.mdx` file.
 *
 * @param absPath Absolute path of the source `.source.fsx` file.
 * @param config Resolved plugin configuration.
 * @param logger Astro logger for warnings and info.
 * @returns Absolute path of the generated `.mdx` file, or `null` if generation was skipped.
 */
async function generateFile(absPath: string, config: ResolvedConfig, logger: AstroIntegrationLogger): Promise<string | null> {
    const source = await fs.readFile(absPath, "utf-8");
    const parsed = tryParse(source);
    if (!parsed) {
        logger.warn(`Skipping ${absPath}: no frontmatter block found`);
        return null;
    }

    const sourceFileName = config.forceLowerCaseOutputFileName ? path.basename(absPath).toLowerCase() : path.basename(absPath);
    const content = [
        parsed.frontMatter,
        "",
        `{/* Generated from ${sourceFileName}. Do not edit — edit ${sourceFileName} instead. */}`,
        "",
        parsed.body,
    ].join("\n");

    const out = mdxPath(absPath, config);
    await fs.mkdir(path.dirname(out), { recursive: true });
    await fs.writeFile(out, content, "utf-8");
    return out;
}

/**
 * Writes a `.gitignore` inside `outputDir` listing every generated `.mdx` file.
 * The file is regenerated from scratch on each call so stale entries are never left behind.
 */
async function generateGitignore(outputDir: string, generatedFiles: string[]): Promise<void> {
    const relPaths = generatedFiles.map((p) => path.relative(outputDir, p));
    const content = [
        "# Generated by starlight-fsharp-literate.",
        "# These files are auto-generated from *.source.fsx files.",
        "# Please include this .gitignore file in your root .gitignore.",
        "",
        ...relPaths,
        "",
    ].join("\n");
    await fs.writeFile(path.join(outputDir, ".gitignore"), content, "utf-8");
}

/** Collect all the sources files, generates all `.mdx` files, and refreshes the `.gitignore`. */
async function generateAll(config: ResolvedConfig, logger: AstroIntegrationLogger): Promise<void> {
    let files: string[];
    try {
        files = await collect(config.sourceDir, config.sourceExtensions);
    } catch {
        logger.warn(`Source directory not found: ${config.sourceDir}`);
        return;
    }

    const results = await Promise.all(files.map((f) => generateFile(f, config, logger)));
    const generated = results.filter((r): r is string => r !== null);
    await generateGitignore(config.outputDir, generated);
}

/**
 * Astro integration that compiles F# Literate (`.source.fsx`) files into `.mdx` files.
 *
 * Files are generated before the content layer runs (`astro:config:setup`) and kept in sync
 * during dev via Vite's file watcher (`astro:server:setup`).
 *
 * @example inline mode — source files live alongside their output in `src/content/docs`:
 *
 * ```ts
 * fsharpLiterate()
 * fsharpLiterate({ mode: "inline", base: "src/content/docs" })
 * ```
 *
 * @example mirror mode — source files mirror `src/content/docs` from a dedicated directory:
 * ```ts
 * fsharpLiterate({ mode: "mirror", sourceDir: "src/content/fsharp-literate", outputDir: "src/content/docs" })
 * fsharpLiterate({ mode: "mirror", sourceExtensions: [".fsx"] }) // only .fsx files
 * ```
 */
export function fsharpLiterate(options?: Options): AstroIntegration {
    const config = resolveConfig(options);
    return {
        name: "starlight-fsharp-literate",
        hooks: {
            "astro:config:setup": async ({ logger }) => {
                await generateAll(config, logger);
            },
            "astro:server:setup": async ({ server, logger }) => {
                const isSourceFile = (p: string) => config.sourceExtensions.some(ext => p.endsWith(ext));
                server.watcher.add(config.sourceDir);
                server.watcher.on("change", async (changedPath: string) => {
                    if (!isSourceFile(changedPath)) return;
                    logger.info(`Regenerating ${path.basename(changedPath)}`);
                    await generateFile(changedPath, config, logger);
                });
                server.watcher.on("add", async (changedPath: string) => {
                    if (!isSourceFile(changedPath)) return;
                    await generateFile(changedPath, config, logger);
                });
                server.watcher.on("unlink", async (changedPath: string) => {
                    if (!isSourceFile(changedPath)) return;
                    const generated = mdxPath(changedPath, config);
                    await fs.rm(generated, { force: true });
                    logger.info(`Removed ${path.basename(generated)}`);
                    const remaining = await collect(config.sourceDir, config.sourceExtensions);
                    await generateGitignore(config.outputDir, remaining.map((f) => mdxPath(f, config)));
                });
            },
        },
    };
}

export default fsharpLiterate;
